services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/src:/app/src
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://dev_user:dev_password@postgresdb:5432/unmatched_dev
      - DOCKER_LOCAL_ADDRESS=http://${DOCKER_LOCAL_ADDRESS:-localhost}:8000
    depends_on:
      - postgresdb

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      - DOCKER_LOCAL_ADDRESS=http://${DOCKER_LOCAL_ADDRESS:-localhost}:3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  postgresdb:
    image: postgres:15
    command: ['postgres', '-c', 'log_statement=all']
    environment:
      - POSTGRES_USER=dev_user
      - PGUSER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=unmatched_dev
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d unmatched_dev -U dev_user']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}
