FROM python:3.9

WORKDIR /app

COPY requirements.txt .
COPY entrypoint.sh /entrypoint.sh

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY /src /src

ENV PYTHONPATH=/app/src

ENTRYPOINT ["/entrypoint.sh"]
CMD uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
