const allIP: Record<string, string[]> = {
  Marvel: ['Brains and Brawn', 'For King and Country', 'Redemption Row', 'Deadpool', "Hell's Kitchen", 'Teen Spirit'],
  'Jurassic Park': ['Jurassic Park - Sattler vs. T-Rex', 'Jurassic Park - Ingen vs. Raptors'],
  'Buffy the Vampire Slayer': ['Buffy the Vampire Slayer'],
};

const allSets: Record<string, string[]> = {
  'Battle of the Legends Vol. 1': ['Medusa', 'Sinbad', 'Alice', 'KingArthur'],
  'Battle of the Legends Vol. 2': ['Achilles', 'BloodyMary', 'SunWukong', 'Yennenga'],
  'Brains and Brawn': ['SpiderMan', 'SheHulk', 'DoctorStrange'],
  'Bruce Lee': ['BruceLee'],
  'Robin Hood vs. Bigfoot': ['RobinHood', 'Bigfoot'],
  'Jurassic Park - Ingen vs. Raptors': ['InGen', 'Raptors'],
  'Cobble & Fog': ['SherlockHolmes', 'Dracula', 'JekyllAndHyde', 'InvisibleMan'],
  'Buffy the Vampire Slayer': ['Buffy', 'Angel', 'Spike', 'Willow'],
  'Little Red Riding Hood vs. Beowulf': ['LittleRed', 'Beowulf'],
  Deadpool: ['Deadpool'],
  'Redemption Row': ['LukeCage', 'GhostRider', 'MoonKnight'],
  "Hell's Kitchen": ['Daredevil', 'Bullseye', 'Elektra'],
  'Jurassic Park - Sattler vs. T-Rex': ['DrSattler', 'TRex'],
  'Houdini vs. The Genie': ['Houdini', 'TheGenie'],
  'Teen Spirit': ['MsMarvel', 'SquirrelGirl', 'CloakAndDagger'],
  'For King and Country': ['BlackWidow', 'BlackPanther', 'WinterSoldier'],
  'Adentures: Tales to Amaze': ['NikolaTesla', 'JillTrent', 'GoldenBat', 'AnnieChristmas'],
  "Sun's Origin": ['OdaNobunaga', 'TomoeGozen'],
  'Slings & Arrows': ['Hamlet', 'Titania', 'WaywardSisters', 'Shakespeare'],
};

const allHeroes: string[] = [
  'Achilles',
  'Alice',
  'Angel',
  'AnnieChristmas',
  'Beowulf',
  'Bigfoot',
  'BlackPanther',
  'BlackWidow',
  'BloodyMary',
  'BruceLee',
  'Buffy',
  'Bullseye',
  'CloakAndDagger',
  'Daredevil',
  'Deadpool',
  'Dracula',
  'DrSattler',
  'DoctorStrange',
  'Elektra',
  'GhostRider',
  'GoldenBat',
  'Hamlet',
  'Houdini',
  'InGen',
  'InvisibleMan',
  'JekyllAndHyde',
  'JillTrent',
  'KingArthur',
  'LittleRed',
  'LukeCage',
  'Medusa',
  'MoonKnight',
  'MsMarvel',
  'NikolaTesla',
  'OdaNobunaga',
  'Raptors',
  'RobinHood',
  'Shakespeare',
  'SheHulk',
  'SherlockHolmes',
  'Sinbad',
  'SpiderMan',
  'Spike',
  'SquirrelGirl',
  'SunWukong',
  'Titania',
  'TheGenie',
  'TomoeGozen',
  'TRex',
  'WaywardSisters',
  'Willow',
  'WinterSoldier',
  'Yennenga',
];

export { allIP, allHeroes, allSets };
